// Daily motivation library for the team. Short, original, sales-minded
// lines written in an energetic, empowering register (the "coach in
// your corner" voice) so we don't republish anyone's copyrighted
// material verbatim. One to two sentences each.
//
// Per project convention: NO em-dashes anywhere in this file's strings,
// since these get posted to Discord (user-visible text).
//
// Selection is deterministic by calendar day (see pickDailyMotivation):
// the same date always yields the same line, the set rotates across the
// year, and nothing repeats within a 365-day window. Deterministic on
// purpose so a cron retry can't double-post a different quote and so the
// behavior is testable.

export const MOTIVATION_QUOTES: string[] = [
  "Today is not a rehearsal. Make the call you have been putting off and watch your week change.",
  "Your next yes is hiding behind the no you almost did not ask for.",
  "Energy sells before words do. Walk in like the answer they have been waiting for.",
  "You do not rise to your goals, you fall to your habits. Build the habit that builds the income.",
  "Every family you protect is a problem you erased before it ever happened.",
  "The market does not pay for activity, it pays for courage applied consistently.",
  "Pick up the phone before you feel ready. Ready is a feeling that follows action, not one that precedes it.",
  "Rejection is not the opposite of success, it is the toll road to it.",
  "A pro is just an amateur who refused to quit on a hard day.",
  "Your prospect cannot feel certainty you do not have. Decide first, then dial.",
  "Discipline is choosing what you want most over what you want right now.",
  "You are one conversation away from a completely different month.",
  "Stop waiting for motivation. Move first, and motivation will run to catch up with you.",
  "The follow-up is where the money lives. Most people knock once and walk away from a full house.",
  "Serve so well that the close feels like a thank you.",
  "Confidence is a memory of times you kept going. Build that memory today.",
  "Small daily reps beat rare heroic efforts every single time.",
  "The fear does not go away. You just get strong enough to bring it with you.",
  "Nobody remembers the call you were nervous about. They remember the help you gave.",
  "Aim higher than comfortable. Comfortable is where dreams go to wait forever.",
  "You were not built to play small. Quit auditioning for a life you can already own.",
  "The best time to follow up was yesterday. The second best time is in the next ten minutes.",
  "Protect the morning and the morning will protect the year.",
  "Talent opens the door. Consistency is what walks you through it for thirty years.",
  "When you help enough families sleep at night, your own future stops keeping you up.",
  "Doubt is loud but it is not in charge. You are.",
  "The deal you lose today is tuition. Show up tomorrow having learned it.",
  "Be the calm in their financial storm and price stops being the conversation.",
  "Hustle without direction is just sweat. Aim, then go all in.",
  "You cannot inspire a client from a place of scarcity. Fill yourself first, then pour.",
  "One more call. That sentence has built more careers than any script ever did.",
  "Greatness is a series of unremarkable days handled with remarkable discipline.",
  "If it scares you a little, it is probably the exact move that grows you.",
  "Your income is a lagging indicator of the conversations you had ninety days ago.",
  "Do the thing badly today so you can do it brilliantly by spring.",
  "The prospect is not buying a policy, they are buying a future they can trust.",
  "Champions are not fearless. They are just faithful to the work when no one is watching.",
  "Your standard, not your potential, decides your paycheck. Raise the standard.",
  "Momentum is a choice you make before breakfast.",
  "You do not need a perfect plan. You need a phone, a list, and the next ten minutes.",
  "Treat every objection like a question wearing a disguise, then answer the real thing.",
  "The size of your why decides the size of the no you can absorb.",
  "Pressure is a privilege. It means you are finally playing a game that matters.",
  "Be so prepared that confidence becomes a side effect.",
  "Today you either feed your goals or feed your excuses. Only one of them grows.",
  "The grind is quiet. The results are loud. Trust the quiet part.",
  "You are not behind. You are one disciplined week from caught up.",
  "Help first, sell second, and the second part stops feeling like selling.",
  "Comparison will steal a good day in seconds. Run your own race at your own pace.",
  "Whatever you are avoiding is usually the one task that pays.",
  "Belief is a skill. Practice it on purpose until it shows up automatically.",
  "The hard call gets easier the moment it is over and never before.",
  "Your future self is begging you to make the call you are negotiating out of.",
  "Show up on the days you do not feel like it. Those are the days that count double.",
  "A no today is not a no forever. It is a not yet with a follow-up date.",
  "Sell the outcome, not the product. People buy peace of mind, not paperwork.",
  "You will never feel fully ready. Brave people just go anyway.",
  "Protect your energy like it is inventory, because it is.",
  "Excellence is boring up close and unforgettable from a distance. Keep stacking the boring days.",
  "The client mirrors your certainty. Decide to be sure before you ever pick up the phone.",
  "Action is the antidote to anxiety. Move and the fog clears.",
  "If the goal does not stretch you, it will not change you.",
  "Be the person who follows up when everyone else gave up. That is the whole edge.",
  "Win the morning with one hard rep and the rest of the day bends your way.",
  "Your network is a garden. Water it before you are hungry for the harvest.",
  "Slumps end the same way they started, one decision at a time.",
  "The dream is free. The discipline is the price. Pay it today.",
  "You are not selling insurance, you are selling the words I am still here to the people they love.",
  "Stop asking if it is possible and start asking who you must become.",
  "Pick the goal that makes you a little nervous to say out loud, then go earn it.",
  "Consistency is more rare than talent and far more profitable.",
  "Make the first call before the doubt finishes its sentence.",
  "Every closed deal started as a conversation someone was scared to start.",
  "Your habits are voting for your future every hour. Check the ballot.",
  "Be coachable. The fastest path forward is the feedback you do not want to hear.",
  "Pressure makes diamonds and quitters. You choose which one daily.",
  "Lead the conversation with curiosity and the close takes care of itself.",
  "You do not find time for what matters. You make it before anything else gets a vote.",
  "The only failed call is the one you talked yourself out of making.",
  "Confidence is built in private and spent in public. Do the private work.",
  "Wake up with a target, not just a to-do list.",
  "When you serve at the level of a leader, the income of a leader follows.",
  "Doubt your doubts as hard as you doubt yourself, then go to work.",
  "The follow-through is the talent. Everyone has the idea.",
  "Be relentless on the activity and relaxed about the outcome.",
  "Your why has to be louder than the alarm clock and stronger than the no.",
  "Today is a deposit into a future you will be proud to spend.",
  "Stop sharpening the axe. The tree is right there. Swing.",
  "People do not buy when they understand you. They buy when they feel understood.",
  "You can have reasons or results. The phone does not accept reasons.",
  "Discomfort is the entry fee for the next version of you. Pay it gladly.",
  "Average is a choice made by skipping the call that felt hard.",
  "The hardest part of any goal is who you must become to deserve it.",
  "Make the ask. The worst they can say leaves you exactly where you are now.",
  "Be early, be prepared, be the one they can count on. That reputation pays forever.",
  "Effort compounds quietly until one day it looks like luck to everyone else.",
  "Your calendar is a confession. Make it confess your priorities.",
  "The best closers are the best listeners who simply did not stop caring.",
  "Win today. Tomorrow is just a longer list of todays.",
  "You are not tired, you are uninspired. Find the why and the energy returns.",
  "A goal without a daily action is just a wish with good lighting.",
  "Bet on the person willing to do today what others will not.",
  "Service is the strategy. Everything else is a tactic.",
  "Your comfort zone is a beautiful place where nothing ever grows.",
  "Talk to one more person than you feel like talking to. That is the whole secret.",
  "Standards protect you on the days motivation does not show up.",
  "The story you tell yourself before the call decides the call.",
  "Be the hardest worker in a quiet room and let the results do the talking.",
  "What you tolerate, you teach. Raise the bar on yourself first.",
  "Fortune favors the follow-up.",
  "Your future is not ahead of you, it is inside the next decision you make.",
  "The professional shows up. The amateur shows up when convenient. Choose.",
  "Help people see what they cannot, then protect what they cannot afford to lose.",
  "Big income is just small disciplines that refused to take a day off.",
  "You will not always be motivated. That is why you build systems and standards.",
  "The phone weighs two ounces and changes entire lives. Lift it.",
  "Do not lower the goal. Raise the effort. Different problem, different fix.",
  "Every master was once a beginner who refused to be embarrassed.",
  "When in doubt, serve. Service has never once led you the wrong way.",
  "You are closer than it feels and further than you will be if you stop.",
  "Make excellence a habit so success cannot be an accident.",
  "Today's discipline is tomorrow's freedom. Trade up.",
  "The client does not care how you feel. They care how much you care. Show it.",
  "Burn the boats on the excuse and watch how creative you get.",
  "Be the reason a family is okay no matter what happens next.",
  "Pressure is just energy waiting for a decision. Decide.",
  "You do not need more time. You need fewer excuses and one more call.",
  "Win the inner game at sunrise and the outer game by sunset.",
  "Your next level is hiding behind a conversation you keep rescheduling.",
  "Be obsessed with the basics. The basics are where the money has always been.",
  "Hard is not a reason to stop. Hard is the reason it pays.",
  "Stop counting the noes and start counting the families you reached.",
  "Confidence is just preparation that ran out of places to hide.",
  "The dip is not a sign to quit. It is the part right before the breakthrough.",
  "Show me your mornings and I will show you your year.",
  "You can be tired or you can be done. Tired sleeps and tries again. Done quits. Be tired.",
  "The opportunity is not coming. It is here, holding a phone, waiting on you.",
  "Sell with conviction or do not pick up the phone. People can hear the difference.",
  "Make the boring call today so you can live the exciting life later.",
  "Your belief is contagious. So is your doubt. Choose what you spread.",
  "The work works. You just have to be there when it does.",
  "One disciplined hour can rescue an entire week. Spend it early.",
  "Be the agent you would want answering the phone for your own family.",
  "Goals are downhill once you decide who is doing the climbing.",
  "Stack one good decision on another until the pile is a career.",
  "You are not stuck. You are committed to a routine that no longer serves you.",
  "Greatness asks for the same thing every day: show up and do not flinch.",
  "Sell the safety, not the spreadsheet. Hearts decide, then heads agree.",
  "The breakthrough usually comes disguised as one more attempt.",
  "If it is important, do it daily. If it is not, stop pretending it is a goal.",
  "Your competition is not other agents. It is the version of you that hits snooze.",
  "Be so good at caring that the close becomes a formality.",
  "Action first. Clarity is a reward for the brave, not a gift for the waiting.",
  "Today you build proof for tomorrow's confidence. Pour the concrete.",
  "Nobody is coming to do it for you, and that is the best news you will get all day.",
  "The list will not call itself. Be the difference between a name and a household protected.",
  "Decide it is going to be a great day before the day gets a vote.",
  "Persistence is just patience with its sleeves rolled up.",
  "You do not have a time problem. You have a priority that has not been made non-negotiable yet.",
  "Talk less about the product and more about the person. They will tell you how to help them.",
  "Champions train on the days the highlight reel is not filming.",
  "The strongest close is a problem genuinely solved.",
  "Your dream does not require permission, only payment in daily effort.",
  "Be too busy serving to notice the fear.",
  "Money follows mastery, and mastery follows reps. Get your reps in.",
  "The hard thing and the right thing are usually wearing the same coat.",
  "Make momentum your first appointment of the day.",
  "If you would not accept that excuse from your hero, do not accept it from yourself.",
  "You are one habit away from a story you will love to tell.",
  "Treat the small client like the big one and the big ones start finding you.",
  "The grind does not care about your mood. Show up anyway and the mood improves.",
  "Be the calmest person in the room and the most prepared. That combination closes.",
  "Your goals can read your calendar. Make sure it inspires them.",
  "Do it tired. Do it unsure. Just do it daily.",
  "The market rewards the brave conversation, not the polished hesitation.",
  "Win the rep in front of you. The career is just a long string of those.",
  "Stop managing your doubts and start outworking them.",
  "Every great month is just an ordinary day repeated with intention.",
  "You were not given this opportunity to be timid with it.",
  "The follow-up call you dread is the commission someone else will gladly take.",
  "Belief without action is just a daydream with good intentions.",
  "Be the professional who returns the call within the hour. That alone beats most of the field.",
  "Your potential does not pay. Your output does. Convert it today.",
  "Make the decision once so you do not have to negotiate it every morning.",
  "A hard conversation handled well is worth a hundred easy ones avoided.",
  "Show up like someone is counting on you, because someone is.",
  "The difference between wanting it and having it is spelled W O R K.",
  "Discipline is self-respect in work clothes.",
  "You do not need a bigger break. You need a smaller excuse.",
  "When you would rather quit, that is the exact moment the work starts paying.",
  "Be the steady hand families remember when everything else felt shaky.",
  "Stop rehearsing the fear and start rehearsing the pitch.",
  "Your habits today are writing the headline of your year. Choose the words.",
  "One brave call can outshine a week of busy work. Make it first.",
  "The professional does not wait to feel like it. The professional begins.",
  "Sell the morning of relief, not the night of the sale.",
  "Comfort is expensive. It costs you the person you could have become.",
  "You have done hard things before. Today is just the newest one.",
  "Be relentless about the inputs and the outputs will stop being mysterious.",
  "The career is built between nine and noon, not in the evening replay.",
  "Caring is a competitive advantage almost nobody is willing to scale.",
  "Run toward the call that scares you. The reward is parked right behind it.",
  "Your why deserves better than the excuse you were about to give it.",
  "Do today what your competition is postponing and you will lap them by summer.",
  "The best version of you is on the other side of the call you are avoiding.",
  "Standards do not take days off, which is exactly why they work.",
  "Be more interested in helping than in impressing and watch trust skyrocket.",
  "Momentum is rented, never owned. Pay the rent this morning.",
  "You cannot pour from an empty tank, so fill your belief before your calendar.",
  "The deal is closed in the preparation. The appointment just confirms it.",
  "Stop waiting for confidence. Build it one completed call at a time.",
  "Hard days are not detours. They are the road.",
  "Make your future proud of the hour you are in right now.",
  "Be the agent whose follow-up feels like being cared for, not chased.",
  "The hardest rep is the first one. Get it done before your brain wakes up.",
  "Your goals are not unrealistic. Your timeline for the effort was.",
  "People buy belief. Bring more of it than they expected.",
  "You will never regret the call you made. Only the one you did not.",
  "Be a thermostat, not a thermometer. Set the energy, do not just read it.",
  "Today is the youngest you will ever be again. Spend the boldness now.",
  "The work whispers before it pays. Keep listening and keep going.",
  "Discipline tastes like discipline today and like freedom in a year.",
  "Bring the energy you wish the room had. They are waiting for someone to.",
  "Your excuse and your dream cannot share the same calendar slot. Pick one.",
  "Be obsessed with serving and the income becomes an accounting detail.",
  "The fastest way through fear is a phone, a name, and a deep breath.",
  "Quietly outwork the noise. Results speak a language excuses cannot.",
  "You are building something. On the slow days, that is still true.",
  "The professional makes the call before the coffee, not after the courage.",
  "Stop polishing the plan and start scuffing it up with action.",
  "When the goal feels far, shrink the timeframe to the next call.",
  "Be the reason someone says I am so glad I answered the phone today.",
  "Your standards are the floor. Make sure the floor is high.",
  "Effort is the only input you fully control. Max it and let go of the rest.",
  "The breakthrough belongs to the one who made it boring to keep going.",
  "Today's no is tomorrow's not-yet and next quarter's yes. Keep the file open.",
  "Be the calm expert, not the anxious salesperson. People follow calm.",
  "You do not need everyone to say yes. You need to ask everyone.",
  "Win the first hour and you have already beaten most of the competition.",
  "Make the dial. Motivation is a story you tell after, not before.",
  "Your future is hiring. The application is filled out in daily reps.",
  "The strong choice is rarely the easy one and always the right one.",
  "Be the agent who shows up the same on day one thousand as on day one.",
  "Effort today is a love letter to the person you are becoming.",
  "Stop asking the goal to get smaller. Ask yourself to get tougher.",
  "The phone is not the enemy. The hesitation is.",
  "Be remarkable on a Tuesday and the big days take care of themselves.",
  "Your career rewards the brave middle, not just the exciting start.",
  "One honest conversation about protection can outlast everything else you do today.",
  "Decide who you are before the day tries to decide for you.",
  "The amateur waits for inspiration. The professional builds it from a checklist.",
  "Be a giver in a world of askers and watch how fast trust compounds.",
  "Your discomfort has a return policy. It pays back in growth, guaranteed.",
  "Make the call you would tell a new agent to make. Then make two more.",
  "The mountain does not get smaller. You get stronger. Start climbing.",
  "Be impossible to ignore by being impossible to outwork.",
  "Today is a brick. Lay it straight and the wall takes care of itself.",
  "The follow-up is not annoying when the intention is to help. Go help.",
  "Your best month is not behind you. It is one disciplined habit ahead.",
  "Stop negotiating with the alarm. Champions get up the first time.",
  "Be the professional who turns a no into a friend and a friend into a referral.",
  "The work is simple. Doing it daily is the rare part. Be rare.",
  "You are not selling. You are guiding people to a decision they will thank you for.",
  "Make the hard call first so the easy ones feel like a reward.",
  "Confidence is just evidence you collected by not quitting.",
  "Be the energy that makes the room sit up. That is a skill, so practice it.",
  "The day does not get easier. You get better. Show up and prove it.",
  "Your goal does not care how you feel. It cares whether you showed up.",
  "Help loudly with your actions and quietly with your ego.",
  "The next call could be the one that changes the whole year. Treat it that way.",
  "Be the kind of professional whose name gets passed around at dinner tables.",
  "Stop waiting for a sign. The phone ringing in your hand is the sign.",
  "Your competition is hoping you sleep in. Disappoint them.",
  "Discipline is a gift you give the person you will be in December.",
  "Be more committed to the work than to the mood. Moods are tourists.",
  "The reps you skip do not disappear. They wait for you as regret.",
  "You are one bold ask away from a story you will tell for years.",
  "Make excellence the minimum and watch your ceiling disappear.",
  "Be the steady professional in an industry full of noise.",
  "The win is in the willingness to start before you feel like it.",
  "Your future does not need a perfect you. It needs a consistent one.",
  "Care enough to follow up a fourth time. That is where the trust is built.",
  "Stop measuring the mountain. Take the next step and the view will change.",
  "Be the reason a family is protected, not the agent they wish had called back.",
  "The dream is loud at night and shy at sunrise. Make it show up for work.",
  "You do not rise on talent. You rise on the days you almost did not show.",
  "Make the call while it still scares you. That is when it counts most.",
  "Be relentless on behalf of the people who do not know they need you yet.",
  "The grind is not punishment. It is the price of a life most people only wish for.",
  "Your standards walked in before you did. Make sure they are tall.",
  "Win the rep, win the hour, win the day. The year is just bookkeeping.",
  "Be the agent who does the unsexy work brilliantly while others wait for easy.",
  "The phone does not get lighter. Your reasons get heavier. Lift it anyway.",
  "You are building a reputation today whether you meant to or not. Build it on purpose.",
  "Make momentum non-negotiable and watch how negotiable everything else becomes.",
  "Be the professional whose follow-up feels like a friend checking in.",
  "The hard part is not knowing what to do. It is doing it again tomorrow.",
  "Your goals are watching your Tuesday, not your New Year's speech.",
  "Decide to be unstoppable today and let the day adjust to that.",
  "Serve like it is personal, because to the family on the other end, it is.",
  "The only call that cannot close is the one never made. Close that gap.",
  "Be too focused on the mission to entertain the doubt.",
  "Today is a chance, not a guarantee. Treat it like the gift it is.",
  "Your effort is the one variable nobody can take from you. Spend it like it matters.",
  "Make the brave choice early so the rest of the day rises to meet it.",
  "Be the calm, the clarity, and the courage your client cannot manufacture alone.",
  "The work you do when nobody claps is the work that eventually gets the standing ovation.",
  "Your next yes does not know your name yet. Go introduce yourself.",
  "Be the professional who treats a slow week like training, not a verdict.",
  "Discipline is just remembering what you really want when something easier shows up.",
  "Make the call. Then make the career out of having always made the call.",
  "Be so prepared and so caring that price becomes the smallest part of the conversation.",
  "The day rewards motion. Stand up, dial out, and let it pay you.",
  "You are not behind your goals. You are early to the version of you that reaches them.",
  "Show up like a closer and the doubts will not recognize the place.",
  "Be the reason today mattered to someone. That is a career worth building.",
  "The work is the prayer and the follow-up is the amen. Do both daily.",
  "Your best is not a peak you visit. It is a standard you keep. Keep it today.",
  "Make the first move on the day before it makes the first move on you.",
  "Be the professional who is hard to rattle and easy to trust.",
  "One more call than yesterday, every day, and the year takes care of itself.",
  "The fear is renting space in your head. Charge it in commissions and evict it with action.",
  "You do not need luck. You need the next ten minutes used on purpose.",
  "Be the agent who finishes the list, not the one who admires it.",
  "The hard road is just the highway with fewer people on it. Enjoy the open lane.",
  "Your future is built in the boring excellence of a normal Wednesday.",
  "Make the call that future you is silently begging you to make right now.",
  "Be relentless, be kind, be early. That trio is nearly unbeatable.",
  "The win was always available. It just required the rep you almost skipped.",
  "Care more than is reasonable and you will close more than is average.",
  "Today is enough time to change a life, including your own. Use it.",
  "Be the professional who makes the hard look routine because the routine was never skipped.",
  "Your goals do not need a pep talk. They need your nine a.m.",
  "Stop waiting to feel like a closer. Close one and the feeling arrives.",
  "Be the steadiest, most prepared person in every conversation and the rest follows.",
  "The day you keep going when you wanted to stop is the day the career truly starts.",
  "Make excellence ordinary for you and you will make results extraordinary for everyone.",
  "Be the reason a family is covered and the reason a teammate believed they could be too.",
  "Your effort compounds in silence and then announces itself all at once. Keep depositing.",
  "The professional makes the call. Everything else is commentary.",
  "You have one job this morning: be braver than your excuses for ten minutes.",
  "Be obsessed with the next right action and bored by the next good excuse.",
  "The harvest is not late. The planting was. Plant today.",
  "Make the hard call and the rest of the day gets out of your way.",
  "Be the agent who turned a Tuesday into a turning point.",
  "Your standard is the speech. Your actions are the audience. Make it loud.",
  "The win is not far. It is just guarded by the call you keep rescheduling.",
  "Be the calm professional who lets results do the bragging.",
  "Show up today like the person you keep promising to become.",
  "The list is a stack of futures waiting for your courage. Start dialing them open.",
  "Be too committed to serve to have time to doubt.",
  "Your year will be decided by mornings like this one. Win it.",
  "Make the call before the story in your head finishes talking you out of it.",
  "Be the professional whose consistency looks like luck to everyone who skipped the reps.",
  "The work does not negotiate. Show up and it pays. Skip it and it remembers.",
  "You are one disciplined day from proud and one excuse from the same spot. Choose proud.",
  "The first call is a cold engine. Make it anyway and watch how fast you warm up.",
  "Protecting one family today is worth more than planning to protect a hundred someday.",
  "Be the professional who treats follow-up like a promise, not a chore.",
  "Your goals are not heavy. Carrying yesterday's excuses is what makes the day feel heavy.",
  "The close is just trust with a signature attached. Earn the trust and the rest is easy.",
  "Outwork your doubts before lunch and they will not bother you by dinner.",
  "Be the one who dials when the office goes quiet. Quiet rooms build loud results.",
  "A single brave conversation can reroute an entire career. Go have it today.",
  "You do not need a better year. You need a better today, repeated until it adds up.",
]

// Voice registers. These are *styles* (the energy of a kind of speaker),
// not attributions. Nothing here is a real person's copyrighted line and
// nothing is signed with their name: every entry below is original copy
// written to evoke a register so the channel does not sound monotone.
// The CEO can recategorize or rewrite any of these in the vault editor.
export type MotivationVoice =
  | 'classic'      // the original AFF house voice (the 365 above)
  | 'decisive'     // Mel-Robbins energy: stop overthinking, move now
  | 'maxout'       // Ed-Mylett energy: one more, raise the standard, faith + work
  | 'state'        // Tony-Robbins energy: decisions, state, massive action
  | 'warmth'       // Zig-Ziglar energy: attitude, serve others first
  | 'courage'      // Brene-Brown energy: show up, be seen, dare anyway
  | 'grit'         // David-Goggins energy: suck it up, stay hard, no excuses

// Original lines written to widen the tonal range. Added on top of the
// 365 classic lines above; the DB seed (MOTIVATION_SEED) is the union.
export const VOICED_QUOTES: { text: string; voice: MotivationVoice }[] = [
  // Decisive (move-now energy)
  { voice: 'decisive', text: "You are not going to feel like it. Do it anyway and let the feeling catch up." },
  { voice: 'decisive', text: "The moment you hesitate, count down from five and dial before you hit one." },
  { voice: 'decisive', text: "Motivation is a coin flip. A decision is a hammer. Pick up the hammer." },
  { voice: 'decisive', text: "You are one decision away from a completely different day. Make it now, not later." },
  { voice: 'decisive', text: "Stop waiting to feel ready. Ready is something you build by starting." },
  { voice: 'decisive', text: "Overthinking is just fear in a nicer outfit. Act before it finishes dressing." },
  { voice: 'decisive', text: "Do not negotiate with the part of you that wants to wait. Move first, debate never." },
  { voice: 'decisive', text: "The five seconds before the hard thing is the whole game. Win those and you win the day." },
  { voice: 'decisive', text: "If you would not let a friend talk themselves out of it, do not let yourself either." },
  { voice: 'decisive', text: "You do not have a knowledge problem. You have a hesitation problem. Close the gap with action." },
  { voice: 'decisive', text: "Your dreams do not respond to feelings. They respond to motion. Start moving." },
  { voice: 'decisive', text: "The hardest part is the deciding. The doing is lighter than the dread, every single time." },
  { voice: 'decisive', text: "Stop researching the call and make it. Clarity lives on the other side of the dial." },
  { voice: 'decisive', text: "You will never feel like changing your life. Do it on a day you do not feel like it." },
  { voice: 'decisive', text: "Hesitation is expensive and action is free. Spend wisely this morning." },
  { voice: 'decisive', text: "Push the button. The thinking was done yesterday. Today is for moving." },

  // Max-out (one-more, raise-the-standard energy)
  { voice: 'maxout', text: "Most people stop at enough. Make one more call and find out who you really are." },
  { voice: 'maxout', text: "Raise your standard and your results have no choice but to follow it up." },
  { voice: 'maxout', text: "Become the person who already has what you want, then act like it before lunch." },
  { voice: 'maxout', text: "Blessed and competitive are not opposites. Be grateful and go take the day anyway." },
  { voice: 'maxout', text: "The person you could become is watching the person you are being right now. Make them proud." },
  { voice: 'maxout', text: "One percent better today is not small. It is the whole future arriving early." },
  { voice: 'maxout', text: "Do not pray for an easier path. Pray to become the kind of person the path needs." },
  { voice: 'maxout', text: "Your standard, not your wish, is what shows up to work. Lift the standard." },
  { voice: 'maxout', text: "Max out today so the version of you in five years sends back a thank you." },
  { voice: 'maxout', text: "Average is comfortable and crowded. The extra rep is where the room opens up." },
  { voice: 'maxout', text: "Outwork the doubt, outlast the dip, and out-serve everyone who quit at noon." },
  { voice: 'maxout', text: "The dream is rent and it is due every single day. Pay it before the day pays you." },
  { voice: 'maxout', text: "You do not get what you want. You get who you become. Go become it today." },
  { voice: 'maxout', text: "One more call when you are tired counts for ten when you are fresh. Make it." },
  { voice: 'maxout', text: "Protect your peace and still bring your fire. You are allowed to have both." },
  { voice: 'maxout', text: "Be so grateful it humbles you and so hungry it moves you. That combination is unstoppable." },

  // State (decisions / energy / massive action)
  { voice: 'state', text: "Change your physiology and you change your call. Stand up, breathe deep, then dial." },
  { voice: 'state', text: "It is not a lack of resources. It is a lack of resourcefulness. Get creative and go." },
  { voice: 'state', text: "The decisions you make in the next hour are quietly designing the next year." },
  { voice: 'state', text: "Massive action drowns out small fears. Do more than feels reasonable today." },
  { voice: 'state', text: "Where focus goes, energy flows. Point it at the next family you can help." },
  { voice: 'state', text: "Progress is the real fuel. Make one inch of it before the doubt wakes up." },
  { voice: 'state', text: "Lower your tolerance for excuses and watch your standard rise on its own." },
  { voice: 'state', text: "Proximity is power. Spend today next to the work, not next to the worry." },
  { voice: 'state', text: "Your state is a choice you make, not a weather report you receive. Choose strong." },
  { voice: 'state', text: "Find the why that makes you cry and the how stops being the problem." },
  { voice: 'state', text: "The map is not the territory. Stop studying the call and go walk into it." },
  { voice: 'state', text: "Model the people who already do it well, then add your relentless on top." },
  { voice: 'state', text: "Turn should into must and watch how fast the excuses pack up and leave." },
  { voice: 'state', text: "Emotion is created by motion. Move the body and the belief comes online." },
  { voice: 'state', text: "Decide once, with everything you have, and you will not have to decide again at noon." },
  { voice: 'state', text: "The quality of your day is the quality of the questions you ask yourself this morning." },

  // Warmth (attitude, serve-others-first)
  { voice: 'warmth', text: "You can have just about anything you want if you help enough people get what they want first." },
  { voice: 'warmth', text: "Your attitude, not your aptitude, will set the altitude of this entire day." },
  { voice: 'warmth', text: "Motivation is like bathing. It does not last, which is exactly why we do it daily." },
  { voice: 'warmth', text: "Failure is an event, never a person. You are not a no, you just heard one." },
  { voice: 'warmth', text: "Do the ordinary things in this business extraordinarily well and you will go far." },
  { voice: 'warmth', text: "People do not care how much you know until they know how much you care. So care, out loud." },
  { voice: 'warmth', text: "You were born to win, but to be the winner you have to plan, prepare, and expect to." },
  { voice: 'warmth', text: "A goal properly set is halfway reached. Set yours before the day sets one for you." },
  { voice: 'warmth', text: "Some people find fault like there is a reward for it. Be the rare one who finds the good." },
  { voice: 'warmth', text: "You do not have to be great to start, but you do have to start to be great. Start now." },
  { voice: 'warmth', text: "Every family you serve well today is a referral you have not been introduced to yet." },
  { voice: 'warmth', text: "The elevator to success is out of order. You are going to have to take the steps, gladly." },
  { voice: 'warmth', text: "Be helpful before you are impressive. Trust grows in that exact order." },
  { voice: 'warmth', text: "Expect the best, prepare for the rest, and pick up the phone with a smile they can hear." },
  { voice: 'warmth', text: "Honesty and hard work will make you a future. Bring both to the very first call." },
  { voice: 'warmth', text: "See the people you serve as souls to help, not sales to close, and watch what comes back." },

  // Courage (show up, be seen, dare anyway)
  { voice: 'courage', text: "Courage is not the absence of fear. It is making the call while the fear is still talking." },
  { voice: 'courage', text: "Vulnerability is not weakness. It is the most honest thing you can bring to a conversation." },
  { voice: 'courage', text: "The critics do not count. The person in the arena, dialing and trying, is the one who matters." },
  { voice: 'courage', text: "You can choose comfort or you can choose growth. You cannot choose both today." },
  { voice: 'courage', text: "Show up and let yourself be seen. That is the bravest sale you will make all day." },
  { voice: 'courage', text: "Clear is kind. Tell people the truth about what they need before it is too late to matter." },
  { voice: 'courage', text: "You are imperfect, you are wired for struggle, and you are absolutely worthy of this goal." },
  { voice: 'courage', text: "Daring greatly means you will get knocked down. Get up where the people you serve can see." },
  { voice: 'courage', text: "Talk to yourself the way you would talk to someone you love and believe in. Then go." },
  { voice: 'courage', text: "Wholehearted work is not flawless work. It is showing up fully even when it is uncertain." },
  { voice: 'courage', text: "Numbing the fear numbs the joy too. Feel it, and make the brave call anyway." },
  { voice: 'courage', text: "The willingness to be seen trying is rarer than talent and worth far more." },
  { voice: 'courage', text: "Connection is why we are here. Make one real one today and the numbers take care of themselves." },
  { voice: 'courage', text: "Shame says you are not enough. The work says watch me. Let the work do the talking." },
  { voice: 'courage', text: "Choose the discomfort of growth over the comfort of staying small and unseen." },
  { voice: 'courage', text: "Brave does not mean unafraid. It means the call gets made with shaky hands and a steady why." },

  // Grit (suck it up, stay hard, no excuses)
  { voice: 'grit', text: "Nobody is coming to make the call for you. That is not bad news, that is your power." },
  { voice: 'grit', text: "When your mind says you are done, you are only about forty percent done. Keep going." },
  { voice: 'grit', text: "Callous your mind on the calls you do not want to make. That is the whole training." },
  { voice: 'grit', text: "Suck it up, pick it up, and dial. The discomfort is the price of the person you are becoming." },
  { voice: 'grit', text: "Stay hard on the days the results are quiet. The quiet days are the ones that pay later." },
  { voice: 'grit', text: "Take souls. Outwork the version of you that wanted to stop and never look back." },
  { voice: 'grit', text: "Motivation is fleeting and weak. Discipline shows up in the rain and dials anyway." },
  { voice: 'grit', text: "You will not always be motivated. Be disciplined, and discipline will carry the day." },
  { voice: 'grit', text: "The work you avoid is the work that builds you. Run straight at the thing you dread." },
  { voice: 'grit', text: "Who is going to carry the load today. You are. So pick it up and stop negotiating." },
  { voice: 'grit', text: "Comfort is the enemy. Get uncomfortable on purpose and watch how fast you grow." },
  { voice: 'grit', text: "Embrace the suck. The hard part is not in the way, the hard part is the way." },
  { voice: 'grit', text: "Do not look for easy. Easy built nobody. Hard is the forge and you are the blade." },
  { voice: 'grit', text: "The only one keeping score that matters is you. Do not let yourself off easy today." },
  { voice: 'grit', text: "When it hurts, that is the rep that counts. Everyone quits right before it pays." },
  { voice: 'grit', text: "No excuses. No shortcuts. Just the next hard call, made on time, every single day." },
]

// The full seed loaded into the DB on first run: the 365 classic lines
// plus the voiced set. Editing happens in the vault after seeding; this
// array is only the starting library and the offline fallback.
export const MOTIVATION_SEED: { text: string; voice: MotivationVoice }[] = [
  ...MOTIVATION_QUOTES.map(text => ({ text, voice: 'classic' as MotivationVoice })),
  ...VOICED_QUOTES,
]

// Deterministic by calendar day: the same date always yields the same
// line from `pool`, the set rotates across the year, and nothing repeats
// within a `pool.length`-day window. Deterministic on purpose so a cron
// retry posts the same line (not a different one) and so it is testable.
// `pool` defaults to the static classic set so callers without DB access
// (and tests) still work; the cron passes the active DB lines instead.
export function pickDailyMotivation(
  date: Date = new Date(),
  pool: string[] = MOTIVATION_QUOTES,
): { text: string; index: number } {
  const safe = pool.length > 0 ? pool : MOTIVATION_QUOTES
  const start = Date.UTC(date.getUTCFullYear(), 0, 0)
  const diff = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) - start
  const dayOfYear = Math.floor(diff / 86_400_000) // 1..366
  const index = (dayOfYear - 1) % safe.length
  return { text: safe[index], index }
}
